include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - sort_child_properties_last
    - prefer_final_locals
    - sized_box_for_whitespace
    - use_build_context_synchronously
    - avoid_void_async
    - camel_case_types
    - file_names
